name: Fadlc
description: Finally a Decent Land Claim
author: Preva1l
version: '${version}'
main: info.preva1l.fadlc.Fadlc
api-version: 1.18

libraries:
  - 'org.redisson:redisson:${redissonVersion}'
  - 'org.apache.commons:commons-pool2:${acp2Version}'
  - 'org.mongodb:mongodb-driver-sync:${mongoVersion}'
  - 'org.xerial:sqlite-jdbc:${sqliteVersion}'
  - 'com.mysql:mysql-connector-j:${mysqlVersion}'
  - 'org.mariadb.jdbc:mariadb-java-client:${mariadbVersion}'
  - 'com.influxdb:influxdb-client-java:${influxdbVersion}'
  - 'de.exlll:configlib-yaml:${configlibVersion}'
  - 'com.zaxxer:HikariCP:${hikariVersion}'

permissions:
  fadlc.user:
    children:
      - fadlc.claim
      - fadlc.profiles
      - fadlc.settings
      - fadlc.particle.default
  fadlc.claim:
    default: true
  fadlc.profiles:
    default: true
  fadlc.settings:
    default: true
  fadlc.particle.default:
    default: true