name: Fadlc
description: Finally a Decent Land Claim
author: Preva1l
version: '${version}'
main: info.preva1l.fadlc.Fadlc
api-version: 1.18

libraries:
  - 'redis.clients:jedis:${jedis_version}'
  - 'org.apache.commons:commons-pool2:${acp2_version}'
  - 'org.mongodb:mongodb-driver-sync:${mongo_version}'
  - 'org.xerial:sqlite-jdbc:${sqlite_version}'
  - 'com.mysql:mysql-connector-j:${mysql_version}'
  - 'org.mariadb.jdbc:mariadb-java-client:${mariadb_version}'
  - 'net.kyori:adventure-text-minimessage:${minimessage_version}'
  - 'net.kyori:adventure-api:${minimessage_version}'
  - 'net.kyori:adventure-platform-bukkit:${mm_platform_version}'
  - 'com.influxdb:influxdb-client-java:${influxdb_version}'
  - 'de.exlll:configlib-yaml:${configlib_version}'
  - 'com.zaxxer:HikariCP:${hikari_version}'

permissions:
  fadlc.claim:
    default: true
  fadlc.particle.default:
    default: true