title: "&8Manage Profiles"

lang:
  back:
    icon: "ARROW"
    model-data: 0
    sound: "click"
    name: "&c&l← Back"
    lore:
      - "&7Click to go back"

  profile:
    sound: "click"
    name: "%profile%"
    lore:
      - "&3Info:"
      - "&7‣ &3Members: &f%members%"
      - "&7‣ &3Border: &f%border%"
      - "&7‣ &3Chunks: &f%chunks%"
      - "&3Flags:"
      - "%flags%"
    flag:
      enabled: "&aEnabled"
      disabled: "&cDisabled"
      format: "&7‣ &3%flag%: &r%status%"

size: 4

layout:
  '10': "PAGINATION_ITEM"
  '11': "PAGINATION_ITEM"
  '12': "PAGINATION_ITEM"
  '13': "PAGINATION_ITEM"
  '14': "PAGINATION_ITEM"
  '15': "PAGINATION_ITEM"
  '20': "PAGINATION_ITEM"
  '21': "PAGINATION_ITEM"
  '22': "PAGINATION_ITEM"
  '23': "PAGINATION_ITEM"
  '24': "PAGINATION_ITEM"